- name: "Gauntlet USDC Core"
  id: "d138d447-4da6-4666-be38-67893193f981"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Gauntlet USDC Core"
  id: "d138d447-4da6-4666-be38-67893193f981"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Gauntlet USDC Core"
  id: "d138d447-4da6-4666-be38-67893193f981"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Gauntlet USDC Core"
  id: "d138d447-4da6-4666-be38-67893193f981"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "Steakhouse sUSDS"
  id: "040fd8ea-a2f9-4616-a649-27774352eb06"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Steakhouse sUSDS"
  id: "040fd8ea-a2f9-4616-a649-27774352eb06"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Steakhouse sUSDS"
  id: "040fd8ea-a2f9-4616-a649-27774352eb06"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Steakhouse sUSDS"
  id: "040fd8ea-a2f9-4616-a649-27774352eb06"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "Spark USDC Vault"
  id: "5ebe85c0-0049-47bd-b6ab-ec913189191a"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Spark USDC Vault"
  id: "5ebe85c0-0049-47bd-b6ab-ec913189191a"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Spark USDC Vault"
  id: "05ebe85c0-0049-47bd-b6ab-ec913189191a"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Spark USDC Vault"
  id: "5ebe85c0-0049-47bd-b6ab-ec913189191a"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "Seamless USDC Vault"
  id: "c21fd59e-a9c1-437e-8a91-fbdfc88d29fd"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Seamless USDC Vault"
  id: "c21fd59e-a9c1-437e-8a91-fbdfc88d29fd"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Seamless USDC Vault"
  id: "c21fd59e-a9c1-437e-8a91-fbdfc88d29fd"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Seamless USDC Vault"
  id: "c21fd59e-a9c1-437e-8a91-fbdfc88d29fd"
  action: "rewards"
  hidden: 0
  whitelist: 
  
- name: "Moonwell Flagship USDC"
  id: "8fbbd2aa-add5-4398-9cae-ba008dbc1764"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Moonwell Flagship USDC"
  id: "8fbbd2aa-add5-4398-9cae-ba008dbc1764"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Moonwell Flagship USDC"
  id: "8fbbd2aa-add5-4398-9cae-ba008dbc1764"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Moonwell Flagship USDC"
  id: "8fbbd2aa-add5-4398-9cae-ba008dbc1764"
  action: "rewards"
  hidden: 0
  whitelist: 
  
- name: "Compound USDC"
  id: "ab292780-630b-40ed-945b-943e6b75286e"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Compound USDC"
  id: "ab292780-630b-40ed-945b-943e6b75286e"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Compound USDC"
  id: "ab292780-630b-40ed-945b-943e6b75286e"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Compound USDC"
  id: "ab292780-630b-40ed-945b-943e6b75286e"
  action: "rewards"
  hidden: 0
  whitelist: 
  
- name: "Compound USDT"
  id: "8b86cff5-49ec-43c3-902c-2268658819b7"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Compound USDT"
  id: "8b86cff5-49ec-43c3-902c-2268658819b7"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Compound USDT"
  id: "8b86cff5-49ec-43c3-902c-2268658819b7"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Compound USDT"
  id: "8b86cff5-49ec-43c3-902c-2268658819b7"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "Sky"
  id: "sky-1"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Sky"
  id: "sky-1"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Sky"
  id: "sky-1"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC.e"
  id: "summer.fi-sonic-usdc.e"
  action: "general"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC.e"
  id: "summer.fi-sonic-usdc.e"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC.e"
  id: "summer.fi-sonic-usdc.e"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC.e"
  id: "summer.fi-sonic-usdc.e"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-base-usdc"
  action: "general"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-base-usdc"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-base-usdc"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-base-usdc"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "summer.fi EURC"
  id: "summer.fi-base-eurc"
  action: "general"
  hidden: 0
  whitelist: 

- name: "summer.fi EURC"
  id: "summer.fi-base-eurc"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "summer.fi EURC"
  id: "summer.fi-base-eurc"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "summer.fi EURC"
  id: "summer.fi-base-eurc"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "summer.fi USDT"
  id: "summer.fi-arbitrum-usdt"
  action: "general"
  hidden: 0
  whitelist: 

- name: "summer.fi USDT"
  id: "summer.fi-arbitrum-usdt"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "summer.fi USDT"
  id: "summer.fi-arbitrum-usdt"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "summer.fi USDT"
  id: "summer.fi-arbitrum-usdt"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-arbitrum-usdc"
  action: "general"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-arbitrum-usdc"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-arbitrum-usdc"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "summer.fi USDC"
  id: "summer.fi-arbitrum-usdc"
  action: "rewards"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-arbitrum-usdt"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-arbitrum-usdt"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-arbitrum-usdt"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-arbitrum-usdc"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-arbitrum-usdc"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-arbitrum-usdc"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-base-usdc"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-base-usdc"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-base-usdc"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-base-eurc"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-base-eurc"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-base-eurc"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-polygon-usdc"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-polygon-usdc"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-polygon-usdc"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-polygon-usdt"
  action: "general"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-polygon-usdt"
  action: "deposit"
  hidden: 0
  whitelist: 

- name: "Fluid"
  id: "fluid-polygon-usdt"
  action: "withdraw"
  hidden: 0
  whitelist: 

- name: "AIbot"
  action: "general"
  hidden: 0
  whitelist: 
    - "0x9F33a4809aA708d7a399fedBa514e0A0d15EfA85"
    - "0x5BaFEAf57Ad6474aDCc720Bd2e724E908AA0d233"
    - "0x628a4c839e1DA864E18cFc635Efb12beA198fb37"
    - "0xe8D98038798C11a0FfFe2c9eEd4f2C28cC04a02A"
    - "0x0D1EADd31aBeD40dc998C271715c9065C6DF8645"
    - "0xeb60A93d35A10730274E837cc5DaB37a6F90B26F"
    - "0xae1FFfB6CCe3636BDAE0383EC40D67a737eDFE94"
    - "0x8f8e18515db74b257C1D2a6b7E25144FdeE7C613"
    - "0x41Bb6b7aCD8f40e5646547B359A3f2B3476e1220"
    - "0x47904b143A66fA5A9554eEd6B72a6179f66aEA4b"
    - "0x1116bFfe122485adDfF8d182CAA91C94B05E490C"
    - "0xdf369630688def597D91D1114649D719848C73C4"
    - "0xa246857d4B4271746a163051cd98c88E3340267f"
    - "0xbeC8A77Ca2edac9a627CE9eB4dD5802b502E9dA6"
    - "0x1481F1D400Fe5fd9dfcE8908981955BbE416041A"
    - "0xf5135CdD47BDF56E4632fdD8De55AC8E092B9C7D"
    - "0x593BdF70304dd6fb907D350a318fFbB8755212d8"
    - "0x5a27EA94C9Cc4f17aF10bDC3d78e4B82a9B9eAA9"
    - "0x2632e9FcD5Ec6c9C67E4CF82F4cFe770e7faE55E"
    - "0x148Bc80c20c6048F9DE619B2655816e64Ab33312"
    - "0x9821FBf42aC75Bb89208c6Eb9AdB0b75942Cd991"
